version: '3.1'
services:
  db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=BHwf3u2n*3bnfyT&
      ports:
        - "5432:5432"
      volumes:
            - data-volume:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 568@duke.edu
      PGADMIN_DEFAULT_PASSWORD: 93n^3rb3q8&hWbe
    ports:
      - '5050:80'
    depends_on:
      - db
  server:
    build: .
    command: python3 main.py
    volumes:
      - '.:/code'
    ports:
      - '12345:12345'
    depends_on:
      - db
volumes:
  data-volume: null